"""add content column to documents

Revision ID: 4208877d8125
Revises: 7ccefcdbe866
Create Date: 2026-08-01 16:18:15.292922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4208877d8125'
down_revision: Union[str, Sequence[str], None] = '7ccefcdbe866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Idempotent like the baseline migration — safe to re-run if a deploy
    # step retries after a partial failure.
    bind = op.get_bind()
    existing_columns = {col["name"] for col in sa.inspect(bind).get_columns("documents")}
    if "content" not in existing_columns:
        op.add_column('documents', sa.Column('content', sa.Text(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'content')
    # ### end Alembic commands ###
