"""baseline: workspaces and documents

Revision ID: 7ccefcdbe866
Revises: 
Create Date: 2026-08-01 15:46:29.163875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ccefcdbe866'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    This is the FIRST Alembic migration adopted on a project that already
    had these two tables in production, created the old way
    (Base.metadata.create_all() on app startup). Alembic has no record of
    that, so this checks what's actually there before creating anything —
    a no-op against the existing production database, but still creates
    both tables correctly on a genuinely fresh database (e.g. a new
    contributor's first local setup). Avoids needing a separate manual
    "alembic stamp" step against production credentials.
    """
    bind = op.get_bind()
    existing_tables = sa.inspect(bind).get_table_names()

    if "workspaces" not in existing_tables:
        op.create_table('workspaces',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('client_name', sa.String(), nullable=False),
        sa.Column('industry', sa.String(), nullable=False),
        sa.Column('employees', sa.Integer(), nullable=False),
        sa.Column('countries', sa.JSON(), nullable=False),
        sa.Column('current_erp', sa.String(), nullable=True),
        sa.Column('current_mes', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )

    if "documents" not in existing_tables:
        op.create_table('documents',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('workspace_id', sa.Integer(), nullable=False),
        sa.Column('filename', sa.String(), nullable=False),
        sa.Column('chunk_count', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
        sa.PrimaryKeyConstraint('id')
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
